version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "33061:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
